import random
from pyrogram import filters
from BrandrdXMusic import app

# List of jokes in Hindi and English, with funny, pun-based, and one-liner categories
JOKES = [
    # Funny (English) - 100
    "Why don’t skeletons fight in school? Because they don’t have the guts! 😂",
    "I told my wife she was drawing her eyebrows too high. She looked surprised! 😲",
    "Why did the scarecrow become a motivational speaker? Because he was outstanding in his field! 🌾",
    "I’m reading a book on anti-gravity. I can’t put it down! 📚",
    "Why don’t eggs tell jokes? They’d crack up! 🥚",
    "I used to be a baker, but I couldn’t make enough dough! 🍞",
    "Why did the tomato turn red? Because it saw the salad dressing! 🍅",
    "I told my computer I needed a break, and now it won’t stop sending me vacation ads! 🏝️",
    "Why don’t programmers prefer dark mode? Because the light attracts bugs! 🐞",
    "I asked my dog what’s two minus two. He said nothing! 🐶",
    "Why did the banana go to the doctor? It wasn’t peeling well! 🍌",
    "I told my friend he’s got a face for radio, but then he got hired as a podcast host! 🎙️",
    "Why don’t some couples play chess? They’re afraid of any situation where a pawn can become a queen! ♟️",
    "I tried to catch some fog, but I mist! 🌫️",
    "Why did the chicken join a band? Because it had the drumsticks! 🐔",
    "I told my boss I’m going to be a comedian. He laughed at me! 😂",
    "Why don’t skeletons go trick-or-treating? They have no body to go with! 💀",
    "I bought a boat because it was on sale—it was a real deal! ⛵",
    "Why did the math book look sad? Because it had too many problems! 📖",
    "I told my friend he’s got a face for TV, but then he became a voice actor! 🎬",
    "Why don’t basketball players go on vacation? Because they’d get called for traveling! 🏀",
    "I tried to write a song about a tortilla, but it turned into a wrap! 🌯",
    "Why did the coffee file a police report? It got mugged! ☕",
    "I told my cat I’m going to be famous. She just yawned! 🐱",
    "Why don’t clocks ever go out of business? Because they keep ticking! ⏰",
    "I tried to make a pencil joke, but it didn’t have a point! ✏️",
    "Why did the orange stop rolling? It ran out of juice! 🍊",
    "I told my girlfriend she’s like a fine wine. She got better with age, but now she’s gone! 🍷",
    "Why don’t some teachers give homework? Because they know you’ll never do it! 📚",
    "I tried to be a vegetarian, but I couldn’t find any beef with it! 🥗",
    "Why did the apple go to school? It wanted to be a little smarter! 🍎",
    "I told my friend he’s got a face for movies, but then he became a stunt double! 🎥",
    "Why don’t some chefs use spices? They’re afraid of getting too saucy! 🌶️",
    "I tried to make a clock joke, but I ran out of time! ⏳",
    "Why did the cucumber blush at the salad party? It overheard the carrots talking about their ‘steamy’ encounter in the stew! 🥒",
    "I told my boss I’m going to be a magician. He said, ‘Good luck disappearing!’ 🎩",
    "Why don’t some dogs chase their tails? They’re too busy chasing their dreams! 🐶",
    "I tried to make a sandwich joke, but it fell flat! 🥪",
    "Why did the lemon go to jail? It couldn’t stop breaking the law! 🍋",
    "I told my friend he’s got a face for comedy, but then he became a clown! 🤡",
    "Why don’t some birds fly south for the winter? They’re too drunk to migrate! 🐦",
    "I tried to make a pizza joke, but it was too cheesy! 🍕",
    "Why did the strawberry blush? It heard the bananas talking about their ‘split’! 🍓",
    "I told my friend he’s got a face for music, but then he became a DJ! 🎧",
    "Why don’t some cats play with yarn? They’re too busy plotting world domination! 🐱",
    "I tried to make a bread joke, but it didn’t rise to the occasion! 🍞",
    "Why did the grape stop in the middle of the road? It was drunk! 🍇",
    "I told my friend he’s got a face for art, but then he became a painter’s model! 🎨",
    "Why don’t some fish swim in schools? They’re too busy being the class clown! 🐟",
    "I tried to make a soup joke, but it was too hot to handle! 🍲",
    "Why did the potato sit alone at the party? It couldn’t find its ‘mash’! 🥔",

    # Funny (Hindi) - 100
    "Skeleton school mein kyun nahi ladte? Kyunki unmein guts hi nahi hai! 😂",
    "Maine apni biwi se kaha uski eyebrows bohot upar hain. Woh surprised dikhne lagi! 😲",
    "Scarecrow motivational speaker kyun bana? Kyunki woh apne khet mein outstanding tha! 🌾",
    "Main anti-gravity pe kitab padh raha hoon. Neeche nahi rakh sakta! 📚",
    "Ande kyun jokes nahi sunate? Kyunki woh crack ho jayenge! 🥚",
    "Main baker tha, par kaafi dough nahi kama saka! 🍞",
    "Tamatar laal kyun ho gaya? Kyunki usne salad dressing dekh li! 🍅",
    "Maine apne computer se kaha mujhe break chahiye, ab woh vacation ads bhejta rehta hai! 🏝️",
    "Programmers dark mode kyun pasand nahi karte? Kyunki light bugs attract karti hai! 🐞",
    "Maine apne kutte se pucha 2 minus 2 kitna hai. Usne kuch nahi kaha! 🐶",
    "Kela doctor ke paas kyun gaya? Kyunki woh theek se peel nahi ho raha tha! 🍌",
    "Maine apne dost se kaha uska chehra radio ke liye perfect hai, par woh podcast host ban gaya! 🎙️",
    "Kuch couples chess kyun nahi khelte? Kyunki unhe darr hai ki pawn queen ban sakta hai! ♟️",
    "Maine fog pakadne ki koshish ki, par main mist ho gaya! 🌫️",
    "Murgina band mein kyun join ki? Kyunki uske paas drumsticks the! 🐔",
    "Maine apne boss se kaha main comedian banunga. Woh hasne laga! 😂",
    "Skeletons trick-or-treating kyun nahi jaate? Kyunki unke paas koi body nahi hota saath jane ke liye! 💀",
    "Maine ek boat kharidi kyunki woh sale pe thi—sach mein deal thi! ⛵",
    "Maths ki kitab dukhi kyun thi? Kyunki usmein bohot problems the! 📖",
    "Maine apne dost se kaha uska chehra TV ke liye perfect hai, par woh voice actor ban gaya! 🎬",
    "Basketball players vacation pe kyun nahi jaate? Kyunki unhe traveling ke liye call kar diya jata hai! 🏀",
    "Maine tortilla pe ek gaana likhne ki koshish ki, par woh wrap ban gaya! 🌯",
    "Coffee ne police report kyun file ki? Kyunki usse mug kar liya gaya! ☕",
    "Maine apni billi se kaha main famous hone wala hoon. Usne bas yawn kiya! 🐱",
    "Ghadiyan business se bahar kyun nahi jaati? Kyunki woh tik-tik karti rehti hain! ⏰",
    "Maine pencil pe joke banane ki koshish ki, par uska koi point nahi tha! ✏️",
    "Santara kyun ruk gaya? Kyunki uska juice khatam ho gaya! 🍊",
    "Maine apni girlfriend se kaha woh fine wine jaisi hai. Woh age ke saath behtar hui, par ab chali gayi! 🍷",
    "Kuch teachers homework kyun nahi dete? Kyunki unhe pata hai tum karoge nahi! 📚",
    "Maine vegetarian banne ki koshish ki, par mujhe koi beef nahi mila! 🥗",
    "Seb school kyun gaya? Kyunki woh thoda aur smart hona chahta tha! 🍎",
    "Maine apne dost se kaha uska chehra movies ke liye perfect hai, par woh stunt double ban gaya! 🎥",
    "Kuch chefs spices kyun nahi use karte? Kyunki unhe darr hai zyada saucy na ho jayein! 🌶️",
    "Maine clock pe joke banane ki koshish ki, par waqt khatam ho gaya! ⏳",
    "Kheera salad party mein kyun sharma gaya? Kyunki usne gajar ko stew mein ‘steamy’ baat karte suna! 🥒",
    "Maine apne boss se kaha main magician banunga. Usne kaha, ‘Good luck disappearing!’ 🎩",
    "Kuch kutte apni poonch kyun nahi pakadte? Kyunki woh sapne pakadne mein busy hote hain! 🐶",
    "Maine sandwich pe joke banane ki koshish ki, par woh flat ho gaya! 🥪",
    "Nimbu jail kyun gaya? Kyunki woh law todta raha! 🍋",
    "Maine apne dost se kaha uska chehra comedy ke liye perfect hai, par woh clown ban gaya! 🤡",
    "Kuch parinde south kyun nahi jaate winter mein? Kyunki woh migrate karne ke liye drunk hote hain! 🐦",
    "Maine pizza pe joke banane ki koshish ki, par woh bohot cheesy ho gaya! 🍕",
    "Strawberry kyun sharma gayi? Kyunki usne kele ko ‘split’ ke baare mein baat karte suna! 🍓",
    "Maine apne dost se kaha uska chehra music ke liye perfect hai, par woh DJ ban gaya! 🎧",
    "Kuch billi yarn se kyun nahi khelti? Kyunki woh duniya pe kabza karne ki planning mein busy hoti hain! 🐱",
    "Maine bread pe joke banane ki koshish ki, par woh rise nahi hua! 🍞",
    "Angoor raaste ke beech mein kyun ruk gaya? Kyunki woh drunk tha! 🍇",
    "Maine apne dost se kaha uska chehra art ke liye perfect hai, par woh painter ka model ban gaya! 🎨",
    "Kuch machhliyan school mein kyun nahi tairti? Kyunki woh class clown banne mein busy hoti hain! 🐟",
    "Maine soup pe joke banane ki koshish ki, par woh bohot garam ho gaya! 🍲",
    "Aloo party mein akela kyun baitha tha? Kyunki usse apna ‘mash’ nahi mila! 🥔",

    # New Funny (English) - 20
    "Why did the smartphone go to therapy? It had too many issues! 📱",
    "I told my fridge it’s too cold, and now it’s giving me the silent treatment! ❄️",
    "Why did the cookie cry? Because its mom was a wafer too far! 🍪",
    "I asked my mirror for advice, but it just reflected my problems! 🪞",
    "Why don’t ghosts use elevators? Because they prefer to take the stairs to haunt! 👻",
    "I tried to dance with my shadow, but it kept stepping on my toes! 🌑",
    "Why did the broom get promoted? It swept the competition away! 🧹",
    "I told my pillow I’m stressed, and it offered me a soft landing! 😴",
    "Why did the bicycle fall over? It was two-tired! 🚲",
    "I asked my socks why they’re always missing, and they said they’re on a roll! 🧦",
    "Why did the lamp blush? It saw the bulb change! 💡",
    "I told my chair to support me, and now it won’t let me stand up! 🪑",
    "Why did the popcorn pop at the party? It wanted to be the life of the bowl! 🍿",
    "I tried to race my snail, but it was too slow to care! 🐌",
    "Why did the umbrella bring a friend? It wanted to share the shade! ☂️",
    "I told my shoes they’re worn out, and they walked away! 👞",
    "Why did the candle go out? It was tired of burning the midnight oil! 🕯️",
    "I asked my clock for time off, and it gave me a second! ⏰",
    "Why did the carrot join the gym? To get a little more shredded! 🥕",
    "I told my blanket it’s too warm, and now it’s giving me space! 🛏️",

    # New Funny (Hindi) - 20
    "Smartphone therapy kyun gaya? Kyunki uske paas bohot issues the! 📱",
    "Maine fridge se kaha woh thanda hai, ab woh chuppi sadh gaya! ❄️",
    "Cookie kyun royi? Kyunki uski mummy wafer door thi! 🍪",
    "Maine mirror se advice maangi, par usne meri problems reflect kar di! 🪞",
    "Bhoot elevator kyun nahi use karte? Kyunki woh stairs se haunt karna pasand karte hain! 👻",
    "Maine apni shadow ke saath dance kiya, par woh mere pair pe chadh gaya! 🌑",
    "Broom promotion kyun mili? Kyunki usne competition ko saaf kar diya! 🧹",
    "Maine pillow se kaha main stressed hoon, usne soft landing offer ki! 😴",
    "Cycle kyun gir gaya? Kyunki woh do-tired ho gaya! 🚲",
    "Maine apne moze se pucha woh kyun gum ho jate hain, unhone kaha roll pe hain! 🧦",
    "Lamp kyun sharma gaya? Kyunki usne bulb change dekha! 💡",
    "Maine chair se kaha mujhe support karo, ab woh mujhe khada nahi hone deta! 🪑",
    "Popcorn party mein kyun pop hua? Kyunki woh bowl ka hero banna chahta tha! 🍿",
    "Maine apne snail ke saath race ki, par woh itna slow tha ki usse parwah nahi! 🐌",
    "Chhatri ne dost kyun bulaya? Shade share karne ke liye! ☂️",
    "Maine apne jute se kaha woh purane hain, unhone chhod diya! 👞",
    "Candle kyun bujh gaya? Kyunki woh midnight oil se thak gaya! 🕯️",
    "Maine clock se time off maanga, usne ek second diya! ⏰",
    "Gajar gym kyun gaya? Thoda shredded hona chahta tha! 🥕",
    "Maine blanket se kaha woh garam hai, ab woh mujhe space de raha hai! 🛏️",
]

@app.on_message(filters.command("joke"))
async def joke(_, message):
    A = await message.reply_text("Fetching a joke for you... 😂")
    # Pick a random joke from the local list
    joke_text = random.choice(JOKES)
    await A.edit(f"🤡 **[Fʀᴏᴍ](https://t.me/ceo_of_secularism)**: {joke_text}", disable_web_page_preview=True)

__MODULE__ = "Jᴏᴋᴇ"
__HELP__ = """
/joke - Gᴇᴛ ᴀ ʀᴀɴᴅᴏᴍ ᴊᴏᴋᴇ"""